spring:
  application:
    name: risk-central-mock-service

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    urls-primary-name: API
    enabled: true
    doc-expansion: list
    filter: true
    show-extensions: true
    url: /v3/api-docs
  show-actuator: true
  use-fqn: true
  cache:
    disabled: false
    ttl: 3600s
  open-api:
    title: CoopCredit Risk Central API
    description: Risk Assessment and Scoring System
    version: "1.0.0"
    contact:
      name: CoopCredit Support
      email: support@coopcredit.com
      url: https://coopcredit.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    terms-of-service: https://coopcredit.com/terms

logging:
  level:
    com.crudzaso.riskapp: INFO
